name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build website
      run: |
        npm run build 2>&1 | tee build.log
        EXIT_CODE=$?
        echo "Exit code: $EXIT_CODE"
        cat build.log
        if [ $EXIT_CODE -ne 0 ]; then
          echo "Compile failed with exit code $EXIT_CODE"
          exit $EXIT_CODE
        fi

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: .github/workflows/blank.yml
